image: baltig.infn.it:4567/epics-containers/epics-py-base

stages:
  - test
  - pypi-publish


before_script:
  # Update pip to the latest version
  - python3 -m pip install --upgrade pip
  - pip install .
  - export PATH=$PATH:$HOME/.local/bin
  - ls $HOME/.local/lib/python3.10/site-packages/jnjrender/template/
test:
  stage: test
  script:
    - |
      supps=$(ls tests/*.j2)
      for k in $supps; do
        echo "* Testing $k"
        jnjrender $k $k.init.yaml --output tests/$k.yaml
        diff tests/$k.yaml tests/refs/$k.yaml
      done

pypi-publish:
  stage: pypi-publish
  script:
    - python3 -m pip install --upgrade build twine
    # Build the package
    - python3 -m build
    # Publish to PyPI
    - python3 -m twine upload dist/* -u $PYPI_USERNAME -p $PYPI_TOKEN
  only:
    - main  # Optional: Restrict this stage to specific branches
  dependencies:
    - beamline-opi-gen